// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebaED01.Model;

#nullable disable

namespace pruebaED01.Migrations
{
    [DbContext(typeof(_dbContext))]
    [Migration("20220929014222_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("pruebaED01.Model.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 28, 20, 42, 22, 173, DateTimeKind.Local).AddTicks(1965));

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("numero_documento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("tipo_persona")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("numero_documento")
                        .IsUnique();

                    b.ToTable("persona", "persona");
                });

            modelBuilder.Entity("pruebaED01.Model.PersonaDireccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("id_persona")
                        .HasColumnType("int");

                    b.Property<int>("id_tipo_direccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_persona");

                    b.HasIndex("id_tipo_direccion");

                    b.ToTable("persona_direccion", "persona");
                });

            modelBuilder.Entity("pruebaED01.Model.PersonaTipoDireccion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tipo_direccion", "persona");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descripcion = "Casa"
                        },
                        new
                        {
                            id = 2,
                            descripcion = "Trabajo"
                        },
                        new
                        {
                            id = 3,
                            descripcion = "Familiar"
                        });
                });

            modelBuilder.Entity("pruebaED01.Model.PersonaDireccion", b =>
                {
                    b.HasOne("pruebaED01.Model.Persona", "Persona")
                        .WithMany("direcciones")
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pruebaED01.Model.PersonaTipoDireccion", "PersonaTipoDireccion")
                        .WithMany()
                        .HasForeignKey("id_tipo_direccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("PersonaTipoDireccion");
                });

            modelBuilder.Entity("pruebaED01.Model.Persona", b =>
                {
                    b.Navigation("direcciones");
                });
#pragma warning restore 612, 618
        }
    }
}
